dist: bionic
language: python
python:
    - 3.8
env:
  global:
    - OWNER=${TRAVIS_REPO_SLUG%/*}
git:
  depth: false
before_install:
  - git tag
install:
  - sudo apt-get -y install libsecp256k1-0
  - pip install -r contrib/requirements/requirements-travis.txt
cache:
  - pip: true
  - directories:
    - /tmp/electrum-build
script:
    - tox
after_success:
    - if [ "$TRAVIS_BRANCH" = "master" ]; then pip install requests && contrib/push_locale; fi
    - coveralls
jobs:
  include:
    - name: "Flake8 linter tests"
      language: python
      install: pip install flake8
      script: flake8 . --count --ignore F821 --select=E9,F63,F7,F82 --show-source --statistics
    - if: branch = bixin_dev
      name: "Native Android build"
      services:
        - docker
      install:
        - while sleep 60; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - sudo docker pull lightningcn/electrum_env:latest
      script:
        # Output something every minute or Travis kills the job
        - while sleep 60; do echo "=====[ $SECONDS seconds still running ]====="; done &
        - sudo docker run --rm -it --name electrum-android-native-builder-cont -v $PWD:/data --workdir=/data/android lightningcn/electrum_env:latest /bin/bash -c "cp ~/android/local.properties local.properties && cp debug.keystore ~/.android/debug.keystore && /data/android/gradlew app:assembleDebug"
        # kill background sleep loop
        - kill %1
        - ls -la android/app/build/outputs/apk/RegTest/debug
        - if [ $(ls android/app/build/outputs/apk/RegTest/debug/ | grep -c bixin-*) -eq 0 ]; then exit 1; fi
      after_success: true 

branches:
  except:
    - travis-build

before_deploy:
  - git tag -f travis-build
  - git remote add gh
    https://${OWNER}:${GITHUB_API_KEY}@github.com/${TRAVIS_REPO_SLUG}.git
  - git push gh :travis-build || true
  - git push -f gh travis-build
  - git remote remove gh

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file_glob: true
  file: 
    - "android/app/build/outputs/apk/MainNet/debug/*.apk"
    - "android/app/build/outputs/apk/MainNet/release/*.apk"
    - "android/app/build/outputs/apk/TestNet/debug/*.apk"
    - "android/app/build/outputs/apk/TestNet/release/*.apk"
    - "android/app/build/outputs/apk/RegTest/debug/*.apk"
    - "android/app/build/outputs/apk/RegTest/debug/*.json"
    - "android/app/build/outputs/apk/RegTest/release/*.apk"
  skip_cleanup: true
  name: electrum android development build (${TRAVIS_BRANCH})
  body: Automatic electrum android development build of $TRAVIS_BRANCH branch (commit $TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    branch: bixin_dev
    tags: false

notifications:
  slack:
    secure: cQ7Bjpd2IbL4YrTK/5YfmHmoxRGd/9TPPjZ94K4HuVCLsSM25JSXg6lsTuPrfriOivJkfW7tbqsr5s+l6croid724G/B/VgzertDg3iB8l9Hlq9PSLMDY6QPTSukuUjVUxpLQs+Go6Z0aN3yGrXx0ATrMP75kdpeV+Z/HdYBi/sVBeiQcskc7KWEMysupRWjYP1fZvs4TQr8icq7bP8vPaXoo9VdfmFRiyTaxOZNhMNRMFu6/LAsu+VlvpvQ7msY/kWx5pi+C1nFSy/nqOKcTcc02h9bbQESgtzOoXRFVoxR7+abkVxSJW5w/tFVc3+2KMfjechh0WQ7YPZ6FQ23+5EIls9hYJHTOKcEgzZJG2XpE2vXuJBWI2ssksAtwROhAgdNgC4r6Ag8izknQPMcAn7pdKpUY35H3OcNPA+R9SaByz7gVo/ejDiw0fshZ9a8jLkmCG4ONSJyoQg6xtbrPGb7jBkJ3cJRe4A43SaeMXGzvTIHR/SqRgbvB0aP4De766f5VBKv7PHftXH8/kPkIRWszaQ8XVCJ+TM+Gh2/21QHNwCscufKDqyv3cs6GLgfEc3kLYV0uog6e1LO8htx+m0hYBDZn1kehknumwAizI+OcorjYxNRTWiZjv7JGtiGfATlI0IP9b7IBxA9FvP335yCNAni4DHtFE383JnuKPE=
  on_success: change  # change: send a notification when the build status changes.
  on_failure: always  # always: always send a notification.
